modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="haisistente"
version="1.0.0"
displayName="Haisistente"
authors="INTEL"
description='''
Adds Haisistentes: tameable companion creatures with GeckoLib animations.
Feed them bamboo to tame them, play music discs to make them dance,
and find their bamboo-jungle village (the Haisillage). Includes a flying
companion with its own inventory and a curable zombie variant.
'''

[[dependencies.haisistente]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"

[[dependencies.haisistente]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.4,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.haisistente]]
    modId="kleidersplayerrenderer"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.haisistente]]
    modId="curios_api"
    mandatory=false
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"
